import "./globals.scss";
import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function NavItem({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <li className={`link link-underline link-underline-black pb-2`}>
      <Link href={href} className={`text-white font-extrabold text-center text-md sm:text-lg px-2`}>
        {children}
      </Link>
    </li>
  );
}

function NavBar() {
  return (
    <div className={`bg-[#0a1228] backdrop-blur-md pb-6 sm:pb-8 px-4 sm:px-16 md:px-20 lg:px-32`}>
      <div className={`emojiWrapper fixed text-4xl blur-[1px] md:blur-[1.25px]`}>
        <p>&#9749;</p> {/* Coffee */}
        <p>&#x1F4BB;</p> {/* Personal Laptop */}
        <p>&#128170;</p> {/* Flexed Bicep */}
        <p>&#127947;</p> {/* Gym */}
        <p>&#129299;</p> {/* Nerd Face */}
        <p>&#9749;</p> {/* Coffee */}
        <p>&#x1F4BB;</p> {/* Personal Laptop */}
      </div>
      <div className={"z-10 relative"}>
        <ul className={`flex items-center justify-center pt-4 sm:justify-start gap-x-4 sm:gap-x-12`}>
          <NavItem href='/'>Home</NavItem>
          <NavItem href='/blogs'>Blogs</NavItem>
        </ul>
        <p className={`pt-12 sm:pt-12 text-[38px] leading-none sm:text-[56px] md:text-[64px] lg:text[72px] text-white font-semibold`}>
          Student Developer
        </p>
        <p className={`text-[18px] sm:text-[20px] text-white font-light sm:font-extralight`}>Ashoka University</p>
      </div>
    </div>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-[#ffffff] text-black mx-auto max-w-full overflow-x-hidden`}>
        <NavBar />
        <div className={`z-10 relative px-4 sm:px-16 md:px-20 lg:px-24 bg-[#ffffff]`}>{children}</div>
      </body>
    </html>
  );
}
